<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use YireoTraining\ExampleHyvaCheckoutStep\Magewire\Checkout\AdditionalSummary;

/** @var $magewire AdditionalSummary */
/** @var Escaper $escaper */

$diet = $magewire->diet;
$comment = $magewire->comment;
?>
<div class="p-6">
    <header class="section-title border-b border-gray-400 pb-1 mb-6">
        <h2 class="text-gray-800 text-xl font-medium">
            <?= __('Additional Details') ?>
        </h2>
    </header>
    <?php if ($comment || $diet): ?>
            <p>
                <strong><?= __('Diet') ?></strong>: <?= $diet ?><br/>
                <strong><?= __('Comment') ?></strong>: <?= $comment ?><br/>
            </p>
    <?php else: ?>
        <p>
            <?= $escaper->escapeHtml(__('No additional details set.')) ?>
        </p>
    <?php endif ?>
</div>
